[package]
name = "gamercade_console"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.131", features = ["derive"] }
bincode = "1.3.3"
winit = "0.26.0"
pixels = "0.8.0"
winit_input_helper = "0.11.0"
rlua = "0.18.0"
parking_lot = "0.11.2"