[package]
name = "gamercade_console"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# GC Dependencies
gamercade_core = { path = "../gamercade_core" }

# General Improvements
hashbrown = "0.12.1"
bytemuck = "1.10.0"
parking_lot = "0.12.1"

# Windowing & Graphics
winit = "0.26.1"
pixels = "0.9.0"
winit_input_helper = "0.12.0"

# Macros & Helpers
text_io = "0.1.10"
strum = { version = "0.24.1", features = ["derive"] }
paste = "1.0.7"

# Serialization / File Loading etc
bincode = "1.3.3"
serde = { version = "1.0.138", features = ["derive"] }

# Scripting
wasmtime = { version = "0.38.1", features = ["cranelift"] }

# Random
nanorand = "0.7.0"

# Audio


# Networking
ggrs = "0.9.1"

# File Picker Dialog
rfd = "0.9.1"