[package]
name = "gamercade-rs"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A safe wrapper around Gamercade's Raw Api"
homepage = "https://gamercade.io"
repository = "https://github.com/gamercade-io/gamercade_rs"
keywords = ["gamedev"]

[dependencies]
paste = "1.0.7"
gamercade_core = { git = "https://github.com/gamercade-io/gamercade_core" }