[package]
name = "gamercade_console"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# General Improvements
hashbrown = "0.12.0"
bytemuck = "1.7.3"
parking_lot = "0.12.0"

# Windowing & Graphics
winit = "0.26.1"
pixels = "0.9.0"
winit_input_helper = "0.11.0"

# Macros & Helpers
text_io = "0.1.9"
strum = { version = "0.23.0", features = ["derive"] }
paste = "1.0.6"

# Serialization / File Loading etc
bincode = "1.3.3"
serde = { version = "1.0.136", features = ["derive"] }

# Scripting
rlua = { version = "0.19.1", features = ["builtin-lua54"] }
wasmer = "2.1.1"

# Audio


# Networking
ggrs = "0.9.0"