[package]
name = "gamercade_audio"
version = "0.1.0"
edition = "2021"
default-run = "tester"

[[bin]]
name = "tester"
path = "src/bin/tester.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.15.0"
serde = { version = "1.0.143", features = ["derive"] }
strum = { version = "0.24.1", features = ["derive"] }
arrayvec = { version = "0.7.2", features = ["serde"] }