[package]
name = "gamercade-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0.7"
gamercade_core = { git = "https://github.com/gamercade-io/gamercade_core" }