[package]
name = "gamercade_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gamercade_core = { path = "../gamercade_core" }

# Serialization
serde = { version = "1.0.136", features = ["derive"] }
bincode = "1.3.3"
serde_json = "1.0.79"