[package]
name = "gamercade_console"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.12.0"
serde = { version = "1.0.136", features = ["derive"] }
bincode = "1.3.3"
winit = "0.26.1"
pixels = "0.9.0"
winit_input_helper = "0.11.0"
rlua = { version = "0.19.1", features = ["builtin-lua54"] }
parking_lot = "0.12.0"