name: Run Tests

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential librust-atk-sys-dev libgtk-3-dev gcc-multilib libpq-dev libxcb-shape0-dev libxcb-xfixes0-dev libasound2-dev portaudio19-dev libpulse-dev libdbus-1-dev
    - name: Run tests
      run: cargo test --verbose